### PR TITLE
Fix 2d material text icons

### PR DESCRIPTION
**Pull request by Laupetin**
Make sure that material text icons that are not 2D do not cause issues anymore.

Also strips material text icons entirely for chat messages and server names in the serverlist.

### CODE REVIEW

**Review by diamante0018 — DISMISSED** [review]
Tested it and it works.

**Comment by Brentdevent** [comment]
Did a quick test. This also seems to fix the fatal error written in issue #112
Good work 👍🏼

**Review by diamante0018 — COMMENTED** [review]
I tested chat as well, and it works. Quick question: I suppose it's also worth stripping the map name as well?

**Comment by Laupetin** [comment]
> I tested chat as well, and it works. Quick question: I suppose it's also worth stripping the map name as well?

Now everything that is displayed in the server list is stripped from material text icons

**Review by Dss0 — APPROVED** [review]

**Pull request merged**
